function s = supported_colors
%supported_colors  Retruns a cell array containing the colors supported by QUATTRO

s = {'Red','Orange','Yellow','Green','Blue','Purple','Sky Blue','Tomato',...
     'Brown','Khaki','Forest','Light Orange','Yellow Green','Lavender'....
     'Light Blue','Teal','Aquamarine','Maroon','Inverse Grey',...
     'Skin','Seashell','Olive','Grey Scale','Slate Blue','Steel Blue'};