function surgery_tools(h_qt)
%surgery_tools  Builds QUATTRO tools for a surgical planning exam
%
%   surgery_tools(h_qt) creates surgical planning exam specific tools for the
%   QUATTRO figure specified by the handle h_qt

% Verify input
if isempty(h_qt) || ~ishandle(h_qt) || ~strcmpi(get(h_qt,'Name'),qt_name)
    error(['QUATTRO:' mfilename ':qtHandleChk'],...
                                            'Invalid handle to QUATTRO figure');
end

% Get handles structure and some color properties
hs = guidata(h_qt);
bkg = get(h_qt,'Color');

% Prepare tools
set(h_qt,'defaultuicontrolbackgroundcolor',bkg,...
         'defaultuicontrolforegroundcolor',[1 1 1],...
         'defaultuicontrolstyle','pushbutton',...
         'defaultuicontrolunits','pixels',...
         'defaultuipanelunits','pixels');
h(1)   = uipanel('Parent',h_qt,...
                 'BackgroundColor',bkg,...
                 'ForegroundColor',[1 1 1],...
                 'Position',[710 470 150 160],...
                 'Tag','uipanel_surgical_planning',...
                 'Title','Surgical Planning Tools',...
                 'Visible','on');
h(2) = uicontrol('Parent',h(1),...
                 'BackgroundColor',bkg*1.2,...
                 'Callback',@create_roi_Callback,...
                 'Position',[10 76 64 64],...
                 'String','Target',...
                 'Tag','pushbutton_point_roi');
surgery_menus(h(2)); %attach context menus
h(3) = uicontrol('Parent',h(1),...
                 'BackgroundColor',bkg*1.2,...
                 'Callback',@show_Callback,...
                 'Position',[10 48 100 22],...
                 'String','3-Plane View',...
                 'Tag','pushbutton_3plane_view');
h(4) = uicontrol('Parent',h(1),...
                 'BackgroundColor',bkg*1.2,...
                 'Callback',@show_Callback,...
                 'Position',[10 21 100 22],...
                 'String','Jump to RAS',...
                 'Tag','pushbutton_jump2ras');

% Store new tools in handles structure
for i = 1:length(h)
    hs.(get(h(i),'Tag')) = h(i);
end
guidata(h_qt,hs);
                 

%-----------------------Callback/Ancillary Functions----------------------------

    function show_Callback(hObj,eventdata) %#ok

        obj = getappdata(h_qt,'qtExamObject');
        if strcmpi(get(hObj,'Tag'),'pushbutton_3plane_view')
            obj.show('3plane','rois','crosshairs');
        elseif strcmpi(get(hObj,'Tag'),'pushbutton_jump2ras')
            jump2ras(h_qt);
        end

    end %show_Callback

end %surgery_tools