function hFig = dceoptsgui(obj)
%dceoptsgui  Creates an interactive GUI for selecting DCE exam options
%
%   dceoptsgui(OBJ) creates an interactive GUI associated with QUATTRO that
%   allows the user to interactively change DCE exam options. Pressing the
%   'escape' key will cancel any actions and pressing the 'enter' key will
%   accept all options.
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

    if nargin<1 || ~strcmpi( class(obj), 'qt_exam' ) || ~obj.isvalid
        error(['QUATTRO:' mfilename ':invalidObjInput'],...
                          'The input must be a valid object of class qt_exam.');
    end

    % Enforce singleton functionality
    if check_singleton(0,'Name','DCE Options')
        return
    end

    % Color setup
    bkg = [93 93 93]/255;

    % Prepare main figure
    hFig = figure('CloseRequestFcn',@(h,ed) delete(h),...
                  'Color',bkg,...
                  'Filename',mfilename,...
                  'IntegerHandle','off',...
                  'MenuBar','None',...
                  'Name','DCE Options',...
                  'NumberTitle','off',...
                  'Position',[520 380 266 520],...
                  'Resize','off',....
                  'Tag','figure_main',...
                  'Units','pixels',...
                  'WindowKeyPressFcn',@options_key_press_Callback,...
                  'WindowStyle','modal');
         set(hFig,'defaultuicontrolhorizontalalignment','right',...
                  'defaultuicontrolbackgroundcolor',bkg,...
                  'defaultuicontrolforegroundcolor',[1 1 1],...
                  'defaultuicontrolfontsize',9,...
                  'defaultuicontrolstyle','checkbox',...
                  'defaultuicontrolunits','pixels',...
                  'defaultuipanelbordertype','etchedin',...
                  'defaultuipanelunits','Pixels',...
                  'defaultuipanelbackgroundcolor',bkg,...
                  'defaultuipanelforegroundcolor',[1 1 1]);
    setappdata(hFig,'examtype',obj.type);
    add_logo(hFig);

    % Prepare UI panels
    hUip(1) = uipanel('Parent',hFig,...
                      'Position',[10 299 246 205],...
                      'Tag','uipanel_pharmacokinetic_model_options',...
                      'Title','Pharmacokinetic Model Options');
    hUip(2) = uipanel('Parent',hFig,...
                      'Position',[10 186 246 104],...
                      'Tag','uipanel_pharmacokinetic_maps',...
                      'Title','Pharmacokinetic Maps');
    hUip(3) = uipanel('Parent',hFig,...
                      'Position',[10 50 246 128],...
                      'Tag','uipanel_t1Correction',...
                      'Title','T1 Correction');

    % Prepare tools
    modelNames = qt_models.package2models(obj.type);
    modelName  = eval([qt_models.model2str(obj.type) '.',...
                                               obj.opts.dceModel '.modelName']);
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@accept_options_Callback,...
              'Position',[60 20 60 22],...
              'String','Accept',...
              'Style','Pushbutton',...
              'Tag','pushbutton_accept');
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@(h,ed) delete(hFig),...
              'Position',[140 20 60 22],...
              'String','Cancel',...
              'Style','pushbutton',...
              'Tag','pushbutton_cancel');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'ForegroundColor',[0 0 0],...
              'Position',[53 160 90 20],...
              'String',modelNames,...
              'Style','PopupMenu',...
              'Tag',[obj.type 'Model'],...
              'Value',find( strcmpi(modelName,modelNames) ));
    uicontrol('Parent',hUip(1),...
              'Position',[156 160 80 20],...
              'String','Multi-Slice',...
              'Tag','multiSlice',...
              'Value',obj.opts.multiSlice);
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','Center',...
              'Position',[37 130 50 20],...
              'String',sprintf('%01.2f',obj.opts.hctArt),...
              'Style','edit',...
              'Tag','hctArt');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','Center',...
              'Position',[184 130 40 20],...
              'String',num2str(obj.opts.injectionTime),...
              'Style','edit',...
              'Tag','injectionTime');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','Center',...
              'Position',[155 100 50 20],...
              'String',num2str(obj.opts.recircTime),...
              'Style','edit',...
              'Tag','recircTime');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','Center',...
              'Position',[155 70 50 20],...
              'String',sprintf('%0.3f',obj.opts.enhanceThresh),...
              'Style','edit',...
              'Tag','enhanceThresh');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','Center',...
              'Position',[150 40 50 20],...
              'String',sprintf('%0.1f',obj.opts.r1),...
              'Style','edit',...
              'Tag','r1');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'ForegroundColor',[0 0 0],...
              'Position',[70 10 90 20],...
              'Style','popupmenu',...
              'String',{'1/s','1/min'},...
              'Tag','dceUnits');
    uicontrol('Parent',hUip(2),...
              'Position',[10 14 80 20],...
              'String','AUC 90',...
              'Tag','iaucMap');
    uicontrol('Parent',hUip(2),...
              'Position',[10 39 80 20],...
              'String','kTrans',...
              'Tag','ktransMap');
    uicontrol('Parent',hUip(2),...
              'Position',[10 64 80 20],...
              'String','kep',...
              'Tag','kepMap');
    uicontrol('Parent',hUip(2),...
              'Position',[159 64 80 20],...
              'String','ve',...
              'Tag','veMap');
    uicontrol('Parent',hUip(2),...
              'Position',[159 39 80 20],...
              'String','vp',...
              'Tag','vpMap');
    uicontrol('Parent',hUip(3),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','center',...
              'Position',[110 71 50 20],...
              'String',sprintf('%0.1f',obj.opts.bloodT10),...
              'Style','edit',...
              'Tag','bloodT10');
    uicontrol('Parent',hUip(3),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'HorizontalAlignment','center',...
              'Position',[110 42 50 20],...
              'String',sprintf('%0.1f',obj.opts.tissueT10),...
              'Style','edit',...
              'Tag','tissueT10');
    uicontrol('Parent',hUip(3),...
              'Position',[150 8 80 20],...
              'String','Use',...
              'Tag','useT1Correction',...
              'Value',obj.opts.useT1Correction);
    uicontrol('Parent',hUip(3),...
              'BackgroundColor',1.2*bkg,...
              'Callback',@import_t10_Callback,...
              'ForegroundColor',[1 1 1],...
              'Position',[15 8 75 22],...
              'String','Import T10',...
              'Style','pushbutton',...
              'Tag','pushbutton_import_t10');

    % Prepare text
    uicontrol('Parent',hUip(1),...
              'Position',[10 157 40 20],...
              'Style','text',...
              'String','Model:',...
              'Tag','text_model');
    uicontrol('Parent',hUip(1),...
              'Position',[10 130 25 18],...
              'Style','text',...
              'String','Hct:',...
              'Tag','text_hctArt');
    uicontrol('Parent',hUip(1),...
              'Position',[91 130 90 18],...
              'Style','text',...
              'String','Base Images:',...
              'Tag','text_injectionTime');
    uicontrol('Parent',hUip(1),...
              'Position',[10 100 134 18],...
              'Style','text',...
              'String','Recirculation Cut-off:',...
              'Tag','text_recirc');
    uicontrol('Parent',hUip(1),...
              'Position',[10 70 134 18],...
              'Style','text',...
              'String','Enhancement Threshold:',...
              'Tag','text_enhanceThresh');
    uicontrol('Parent',hUip(1),...
              'Position',[10 40 134 18],...
              'Style','text',...
              'String','Gd Relaxivity (/sec/mM):',...
              'Tag','text_r1');
    uicontrol('Parent',hUip(1),...
              'Position',[10 10 58 17],...
              'Style','text',...
              'String','PK Units:',...
              'Tag','text_dceUnits');
    uicontrol('Parent',hUip(3),...
              'Position',[8 70 100 20],...
              'String','Blood T10 (ms):',...
              'Style','text',...
              'Tag','text_bloodT10');
    uicontrol('Parent',hUip(3),...
              'Position',[8 40 100 20],...
              'String','Tissue T10 (ms):',...
              'Style','text',...
              'Tag','text_tissueT10');

    % Define the maximum value for the "injectionTime" text box
    setappdata( findobj(hFig,'Tag','injectionTime'),'editMax',size(obj.imgs,2)-1 );

    % Set the standard application data
    setappdata(hFig,'qtExamObject',obj);
    setappdata(hFig,'qtOptsObject',obj.opts);

    % All tools have been initialized at this point. Update the application data
    set_ui_current_value(hFig);

end %dceoptsgui


%-------------------------Callback Functions------------------------------------

function import_t10_Callback(hObj,eventdata)

    % Request files from user
    fName = uigetfile;

end %import_t10_Callback