function hFig = mapoptsgui(obj)
%mapoptsgui  Creates an interactive GUI for selecting various map exam options
%
%   mapoptsgui creates an interactive GUI associated with QUATTRO that allows
%   the user to interactively change various map exam options. Pressing the
%   'escape' key will cancel any actions and pressing the 'enter' key will
%   accept all options. OBJ is a valid qt_exam object.
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

    if nargin<1 || ~strcmpi( class(obj), 'qt_exam' ) || ~obj.isvalid
        error(['QUATTRO:' mfilename ':invalidObjInput'],...
                          'The input must be a valid object of class qt_exam.');
    end

    % Enforce singleton functionality
    if check_singleton(0,'Name','Model Parameter Options')
        return
    end

    % Color setup
    bkg = [93 93 93]/255;

    % Prepare main figure
    hFig = figure('CloseRequestFcn',@(h,ed) delete(h),...
                  'Color',bkg,...
                  'Filename',mfilename,...
                  'IntegerHandle','off',...
                  'MenuBar','None',...
                  'Name','Model Parameter Options',...
                  'NumberTitle','off',...
                  'Position',[520 380 266 460],...
                  'Resize','off',....
                  'Tag','figure_main',...
                  'Units','pixels',...
                  'WindowKeyPressFcn',@options_key_press_Callback,...
                  'WindowStyle','modal');
         set(hFig,'defaultuicontrolhorizontalalignment','right',...
                  'defaultuicontrolbackgroundcolor',bkg,...
                  'defaultuicontrolforegroundcolor',[1 1 1],...
                  'defaultuicontrolfontsize',9,...
                  'defaultuicontrolstyle','checkbox',...
                  'defaultuicontrolunits','pixels',...
                  'defaultuipanelbordertype','etchedin',...
                  'defaultuipanelunits','Pixels',...
                  'defaultuipanelbackgroundcolor',bkg,...
                  'defaultuipanelforegroundcolor',[1 1 1]);
    setappdata(hFig,'examtype',obj.type);
    add_logo(hFig);

    % Grab the handles structure for updating the initial GUI values
    hs = guihandles(hFig);

    % Set the options
    mapOpts = {};
    cellfun(@(x) assign_values(hs.(x),obj.opts.(x)),mapOpts);

    % Set the standard application data
    setappdata(hFig,'qtExamObject',obj);
    setappdata(hFig,'qtOptsObject',obj.opts);
    setappdata(hFig,'optionNames',mapOpts);

    % All tools have been initialized at this point. Update the application data
    set_ui_current_value(hFig);

end %mapoptsgui