function hFig = multiteoptsgui(obj)
%multiteoptsgui  Creates an interactive GUI for selecting multi-TE exam options
%
%   multiteoptsgui(OBJ) creates an interactive GUI associated with QUATTRO
%   that allows the user to interactively change multiple echo time exam
%   options. Pressing the 'escape' key will cancel any actions and pressing the
%   'enter' key will accept all options. OBJ is a valid qt_exam object
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

    if nargin<1 || ~strcmpi( class(obj), 'qt_exam' ) || ~obj.isvalid
        error(['QUATTRO:' mfilename ':invalidObjInput'],...
                          'The input must be a valid object of class qt_exam.');
    end

    % Enforce singleton functionality
    if check_singleton(0,'Name','Multi-TE Options')
        return
    end

    % Color set up
    bkg = [93 93 93]/255;

    % Prepare main figure
    hFig = figure('CloseRequestFcn',@(h,ed) delete(h),...
                   'Color',bkg,...
                   'Filename',mfilename,...
                   'IntegerHandle','off',...
                   'MenuBar','None',...
                   'Name','Multi-TE Options',...
                   'NumberTitle','off',...
                   'Position',[520 380 266 250],...
                   'Resize','off',....
                   'Tag','figure_main',...
                   'Units','pixels',...
                   'WindowKeyPressFcn',@options_key_press_Callback,...
                   'WindowStyle','modal');
         set(hFig,'defaultuicontrolhorizontalalignment','right',...
                   'defaultuicontrolbackgroundcolor',bkg,...
                   'defaultuicontrolforegroundcolor',[1 1 1],...
                   'defaultuicontrolfontsize',9,...
                   'defaultuicontrolstyle','checkbox',...
                   'defaultuicontrolunits','pixels',...
                   'defaultuipanelbordertype','etchedin',...
                   'defaultuipanelunits','Pixels',...
                   'defaultuipanelbackgroundcolor',bkg,...
                   'defaultuipanelforegroundcolor',[1 1 1]);
    setappdata(hFig,'examtype',obj.type);
    add_logo(hFig);

    % Prepare UI panels
    hUip(1) = uipanel('Parent',hFig,...
                      'Position',[10 50 246 180],...
                      'Tag','uipanel_multite_model_options',...
                      'Title','Multi-TE Model Options');
    hUip(2) = uipanel('Parent',hUip(1),...
                      'Position',[10 73 226 85],...
                      'Tag','uipanel_maps',...
                      'Title','Map Options');

    % Prepare tools
    mObj = eval(obj.type);
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@accept_options_Callback,...
              'Position',[60 10 60 22],...
              'String','Accept',...
              'Style','Pushbutton',...
              'Tag','pushbutton_accept');
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@(h,ed) delete(hFig),...
              'Position',[140 10 60 22],...
              'String','Cancel',...
              'Style','pushbutton',...
              'Tag','pushbutton_cancel');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@change_model_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[92 46 90 20],...
              'String',mObj.modelNames,...
              'Style','PopupMenu',...
              'Tag',[obj.type 'Model']);
    uicontrol('Parent',hUip(1),...
              'Position',[84 13 80 20],...
              'String','Multi-Slice',...
              'Tag','multiSlice');
    uicontrol('Parent',hUip(2),...
              'Position',[15 15 70 20],...
              'String','T2 (ms)',...
              'Tag','t2Map');
    uicontrol('Parent',hUip(2),...
              'Position',[125 45 70 20],...
              'String','S0 (a.u.)',...
              'Tag','s0Map');
    uicontrol('Parent',hUip(2),...
              'Position',[15 45 70 20],...
              'String','R2 (1/s)',...
              'Tag','r2Map');

    % Prepare text
    uicontrol('Parent',hUip(1),...
              'Position',[10 44 80 20],...
              'Style','text',...
              'String','Model:',...
              'Tag','text_model');

    % Grab the handles structure for updating the initial GUI values
    hs = guihandles(hFig);

    % Set options
    vteOpts = {'multiteModel',...
               'multiSlice',...
               't2Map',...
               's0Map',...
               'r2Map'};
    cellfun(@(x) assign_values(hs.(x),obj.opts.(x)),vteOpts);

    % Set the standard application data
    setappdata(hFig,'qtExamObject',obj);
    setappdata(hFig,'qtOptsObject',obj.opts);
    setappdata(hFig,'optionNames',vteOpts);

    % All tools have been initialized at this point. Update the application data
    set_ui_current_value(hFig);

end %multiteoptsgui