function hFig = multitioptsgui(obj)
%multitioptsgui  Creates an interactive GUI for selecting VTI exam options
%
%   multitioptsgui(OBJ) creates an interactive GUI associated with QUATTRO that
%   allows the user to interactively variable TI exam options. Pressing the
%   'escape' key will cancel any actions and pressing the 'enter' key will
%   accept all options. OBJ is a valid qt_exam object
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

    % Validate the qt_exam object input
    if nargin<1 || ~strcmpi( class(obj), 'qt_exam' ) || ~obj.isvalid
        error(['QUATTRO:' mfilename ':invalidObjInput'],...
                          'The input must be a valid object of class qt_exam.');
    end

    % Enforce singleton functionality
    if check_singleton(0,'Name','Multi-TI Options')
        return
    end

    % Color set up
    bkg = [93 93 93]/255;

    % Prepare main figure
    hFig = figure('CloseRequestFcn',@(h,ed) delete(h),...
                  'Color',bkg,...
                  'Filename',mfilename,...
                  'IntegerHandle','off',...
                  'MenuBar','None',...
                  'Name','Multi-TI Options',...
                  'NumberTitle','off',...
                  'Position',[520 380 266 250],...
                  'Resize','off',....
                  'Tag','figure_main',...
                  'Units','pixels',...
                  'WindowKeyPressFcn',@options_key_press_Callback,...
                  'WindowStyle','modal');
         set(hFig,'defaultuicontrolhorizontalalignment','right',...
                  'defaultuicontrolbackgroundcolor',bkg,...
                  'defaultuicontrolforegroundcolor',[1 1 1],...
                  'defaultuicontrolfontsize',9,...
                  'defaultuicontrolstyle','checkbox',...
                  'defaultuicontrolunits','pixels',...
                  'defaultuipanelbordertype','etchedin',...
                  'defaultuipanelunits','Pixels',...
                  'defaultuipanelbackgroundcolor',bkg,...
                  'defaultuipanelforegroundcolor',[1 1 1]);
    setappdata(hFig,'examtype',obj.type);
    add_logo(hFig);

    % Prepare UI panels
    hUip(1) = uipanel('Parent',hFig,...
                      'Position',[10 50 246 180],...
                      'Tag','uipanel_multitiModel_options',...
                      'Title','Multi-TI Model Options');
    hUip(2) = uipanel('Parent',hUip(1),...
                      'Position',[10 73 226 85],...
                      'Tag','uipanel_maps',...
                      'Title','Map Options');

    % Prepare tools
    modelNames = qt_models.package2models(obj.type);
    modelName  = eval([qt_models.model2str(obj.type) '.',...
                                         obj.opts.multitiModel '.modelName']);
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@accept_options_Callback,...
              'Position',[60 10 60 22],...
              'String','Accept',...
              'Style','Pushbutton',...
              'Tag','pushbutton_accept');
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@(h,ed) delete(hFig),...
              'Position',[140 10 60 22],...
              'String','Cancel',...
              'Style','pushbutton',...
              'Tag','pushbutton_cancel');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@change_model_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[92 46 90 20],...
              'String',modelNames,...
              'Style','PopupMenu',...
              'Tag',[obj.type 'Model'],...
              'Value',find( strcmpi(modelName,modelNames) ));
    uicontrol('Parent',hUip(1),...
              'Position',[10 14 130 20],...
              'String','Polarity Correction',...
              'Tag','usePolarityCorrection',...
              'Value',obj.opts.usePolarityCorrection);
    uicontrol('Parent',hUip(1),...
              'Position',[153 13 80 20],...
              'String','Multi-Slice',...
              'Tag','multiSlice',...
              'Value',obj.opts.multiSlice);
    uicontrol('Parent',hUip(2),...
              'Position',[15 45 60 20],...
              'String','T1 (ms)',...
              'Tag','t1Map',...
              'Value',obj.opts.t1Map);
    uicontrol('Parent',hUip(2),...
              'Position',[125 45 70 20],...
              'String','S0 (a.u.)',...
              'Tag','s0Map',...
              'Value',obj.opts.s0Map);
    uicontrol('Parent',hUip(2),...
              'Position',[125 15 75 20],...
              'String','Flip Angle',...
              'Tag','flipAngleMap',...
              'Value',obj.opts.flipAngleMap);
    uicontrol('Parent',hUip(2),...
              'Position',[15 15 75 20],...
              'String','R1 (1/ms)',...
              'Tag','r1Map',...
              'Value',obj.opts.r1Map);

    % Prepare text
    uicontrol('Parent',hUip(1),...
              'Position',[10 44 80 20],...
              'Style','text',...
              'String','Model:',...
              'Tag','text_model');

    % Set the standard application data
    obj.register(hFig);
    setappdata(hFig,'qtOptsObject',obj.opts);

    % Determine flip angle checkbox functionality
%     change_model_Callback( findobj(hFig,'Tag','multitiModel'), [] );

    % All tools have been initialized at this point. Update the application data
    set_ui_current_value(hFig);

end %multitioptsgui

%------------------------------Callback Functions-------------------------------

function change_model_Callback(hObj,~)

    % Get options object
    hFig = guifigure(hObj);

    % Enable\disable tools
    hChk = findobj(hFig,'Tag','flipAngleMap');
    if ~any(get(hObj,'Value')==3:4)
        set(hChk, 'Enable','off', 'Value',false);
    else
        set(hChk, 'Enable','on');
    end

end %change_model_Callback