function rois = roiimporttool(varargin)
%roiimporttool  QUATTRO tool for importing ROIs
%
%   ROI = roiimporttool(OBJ) creates an interactive GUI associated with the
%   qt_exam object OBJ that allows the user to interactively import ROIs,
%   adjusting the scaling and position at which the ROIs are stored within the
%   exam object

% Parse inputs
%TODO: this needs to be more/less sophisticated depending on the needs of this
%GUI
obj = varargin{1};

% Verify the caller
callerType = class(obj);
if ~nargin || ~strcmpi(callerType,'qt_exam') || isempty(obj) || ~isvalid(obj)
    error(['QUATTRO:' mfilename ':invalidExamObj'],...
                   'A valid qt_exam object must be passed as the first input.');
end

% Prepare the figure properties and determine the new figure's position based on
% the current location of QUATTRO
figPos = [520 374 586 263];

% Color setup
bkg = ones(1,3) * (93/255);

% Prepare the main figure
hFig = figure('Color',bkg,...
              'Filename',mfilename,...
              'IntegerHandle','off',...
              'MenuBar','None',...
              'Name','QUATTRO:: ROI Import ::',...
              'NumberTitle','off',...
              'Position',figPos,...
              'Resize','on',...
              'Tag','figure_main',...
              'Units','Pixels');
set(hFig,'defaultuicontrolunits','pixels',...
         'defaultuicontrolbackgroundcolor',[1 1 1],...
         'defaultuicontrolfontsize',9,...
         'defaultuipanelbordertype','etchedin',...
         'defaultuipanelbackgroundcolor',bkg);
add_logo(hFig);

% Create the UI tools
uicontrol('Parent',hFig,...
          'Callback',identityFcn,...
          'Enable','on',...
          'Position',[10 10 69 22],...
          'String','Accept',...
          'Style','pushbutton',...
          'Tag','pushbutton_accept');
uicontrol('Parent',hFig,....
          'Callback',@add_file_Callback,...
          'Enable','on',...
          'Position',[507 10 69 22],...
          'String','Add File(s)',...
          'Style','pushbutton',...
          'Tag','pushbutton_add_file');

% Prepare UI context menus
hCmenu = uicontextmenu;
uimenu(hCmenu,'Callback',@delete_imported_roi,...
              'Enable','off',...
              'Label','Delete',...
              'Tag','context_delete_roi');
uimenu(hCmenu,'Callback',@preview_imported_roi,...
              'Enable','off',...
              'Label','Preview',...
              'Tag','ocntext_preview_roi');

% Create the import table
hTable = uitable('Parent',hFig,...
                 'CellEditCallback',@import_table_Callback,...
                 'ColumnEditable',true,...
                 'ColumnFormat',{'char','char','numeric','numeric','numeric','numeric','char'},...
                 'ColumnName',{'File Name','Type','X Size','Y Size','Slice','Series','Color'},...
                 'FontSize',10,...
                 'Position',[10 42 566 212],...
                 'Tag','table_roi_import',...
                 'uicontextmenu',hCmenu);
addlistener(hTable,'Data','PostSet',@new_roi_import_data);

% Store the qt_exam object
setappdata(hFig,'qtExamObject',obj);

end %roiimporttool


%-----------------------Callback/Ancillary Functions----------------------------

function add_file_Callback(hObj,eventdata)
end %add_file_Callback