function three_plane_viewer(hQt)
%three_plane_viewer  Allows 3-plane visualization of a 3D volume in QUATTRO
%
%   three_plane_viewer(h_qt) creates an interactive GUI associated wtih QUATTRO
%   that allows the user to visualize a 3D image volume. Two green lines, which
%   mark the current location in the imaging volume, are displayed on each of
%   the images, marking the locations of QUATTRO in those two orthogonal views.
%   If targets have been placed, those will be visualized similarly with red
%   lines.
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

if nargin<1 || ~ishandle(hQt) || ~strcmpi(get(hQt,'Name'),qt_name)
    error(['QUATTRO:' mfilename ':inputChk'],'Invalid QUATTRO figure handle.');
end

% Enforce singleton functionality
obj = getappdata(hQt,'qtExamObject');
if ~isempty(obj.h_view_fig) && ishandle(obj.h_view_fig)
    figure(obj.h_view_fig);
    return
end

% Color setup
bkg = [93 93 93]/255;

% Prepare main figure
qt_pos = get(hQt,'Position'); %use QUATTRO position to place new window on same monitor
fig_pos = [qt_pos(1:2) 808 420];
h_fig = figure('CloseRequestFcn',@delete_fig_main,...
               'Color',          bkg,...
               'Filename',       mfilename,...
               'IntegerHandle',  'off',...
               'MenuBar',        'None',...
               'Name',           '3-Plane Viewer',...
               'NumberTitle',    'off',...
               'Position',       fig_pos,...
               'Tag',            'figure_main',...
               'Toolbar',        'figure',...
               'Units',          'Pixels');
     set(h_fig,'defaultaxescolor',     [1 1 1],...
               'defaultaxesxcolor',    [1 1 1],...
               'defaultaxesycolor',    [1 1 1],...
               'defaultaxesunits',     'normalized',...
               'defaultaxesxticklabel','',...
               'defaultaxesyticklabel','');
h_tools = findall( findall(h_fig,'Type','uitoolbar') );
delete(h_tools([2:7 9 13:17]));
setappdata(h_fig,'qtExamObject',obj);   %cache exams object
setappdata(h_fig,'linkedfigure',hQt); %link to QUATTRO
add_logo(h_fig);

% Prepare display
axes('Parent',h_fig,...
     'Position',[276 80 256 256]./[fig_pos(3:4) fig_pos(3:4)],...
     'Tag','axes1');
axes('Parent',h_fig,...
     'Position',[542 80 256 256]./[fig_pos(3:4) fig_pos(3:4)],...
     'Tag','axes2');
axes('Parent',h_fig,...
     'Position',[10  80 256 256]./[fig_pos(3:4) fig_pos(3:4)],...
     'Tag','axes3');

% Update exams object
obj.update(h_fig);