function hFig = useroptsgui(obj)
%useroptsgui  Creates an interactive GUI for selecting general QUATTRO options
%
%   useroptsgui(OBJ) creates an options GUI associated with QUATTRO that allows
%   the user to interactively change basic user preferences. Pressing the
%   'escape' key will cancel any actions and pressing the 'enter' key will
%   accept all options. OBJ is a valid qt_exam object
%
%       ~Note: functionality of this GUI is not supported outside of QUATTRO

    if nargin<1 || ~strcmpi( class(obj), 'qt_exam' ) || ~obj.isvalid
        error(['QUATTRO:' mfilename ':invalidObjInput'],...
                          'The input must be a valid object of class qt_exam.');
    end

    % Enforce singleton functionality
    if check_singleton(0,'Name','QUATTRO Options')
        return
    end

    % Color setup and exams object retrevial
    bkg = [93 93 93]/255;

    % Prepare main figure
    hFig = figure('CloseRequestFcn',@(h,ed) delete(h),...
                  'Color',bkg,...
                  'Filename',mfilename,...
                  'IntegerHandle','off',...
                  'MenuBar','None',...
                  'Name','QUATTRO Options',...
                  'NumberTitle','off',...
                  'Position',[520 379 220 471],...
                  'Resize','off',....
                  'Tag','figure_main',...
                  'Units','pixels',...
                  'WindowKeyPressFcn',@options_key_press_Callback,...
                  'WindowStyle','modal');
         set(hFig,'defaultuicontrolunits','pixels',...
                  'defaultuicontrolstyle','checkbox',...
                  'defaultuicontrolhorizontalalignment','left',...
                  'defaultuicontrolbackgroundcolor',bkg,...
                  'defaultuicontrolforegroundcolor',[1 1 1],...
                  'defaultuicontrolfontsize',9,...
                  'defaultuipanelbordertype','etchedin',...
                  'defaultuipanelunits','Pixels',...
                  'defaultuipanelbackgroundcolor',bkg,...
                  'defaultuipanelforegroundcolor',[1 1 1]);
    setappdata(hFig,'examtype',obj.type);
    add_logo(hFig);

    % Prepare UI panels
    hUip(1) = uipanel('Parent',hFig,...
                      'Position',[10 365 200 100],...
                      'Tag','uipanel_resources',...
                      'Title','Computer Resources');
    hUip(2) = uipanel('Parent',hFig,...
                      'Position',[10 190 200 168],...
                      'Tag','uipanel_directories',...
                      'Title','Data Directories');
    hUip(3) = uipanel('Parent',hFig,...
                      'Position',[10 43 200 140],...
                      'Tag','upanel_exam_options',...
                      'Title','Basic Exam Options');

    % Prepare tools
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@accept_options_Callback,...
              'ForegroundColor',[1 1 1],...
              'Position',[30 10 70 22],...
              'String','Accept',...
              'Style','Pushbutton',...
              'Tag','pushbutton_accept');
    uicontrol('Parent',hFig,...
              'BackgroundColor',1.2*bkg,...
              'Callback',@(h,ed) delete(hFig),...
              'ForegroundColor',[1 1 1],...
              'Position',[120 10 70 22],...
              'String','Cancel',...
              'Style','pushbutton',...
              'Tag','pushbutton_cancel');
    uicontrol('Parent',hUip(1),...
              'Callback',@parallel_Callback,...
              'Enable','off',...
              'Position',[10 50 150 20],...
              'String','Parallel Computation',...
              'Tag','parallel');
    uicontrol('Parent',hUip(1),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[100 25 40 20],...
              'Style','edit',...
              'Tag','nProcessors',...
              'Visible','off');
    uicontrol('Parent',hUip(2),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[10 104 180 22],...
              'Style','edit',...
              'Tag','loadDir');
    uicontrol('Parent',hUip(2),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[10 57 180 22],...
              'Style','edit',...
              'Tag','saveDir');
    uicontrol('Parent',hUip(2),...
              'BackgroundColor',[1 1 1],...
              'Callback',@edit_options_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[10 10 180 22],...
              'Style','edit',...
              'Tag','importDir');
    uicontrol('Parent',hUip(3),...
              'BackgroundColor',[1 1 1],...
              'Callback',@dictionary_Callback,...
              'ForegroundColor',[0 0 0],...
              'Position',[85 52 95 20],...
              'Style','popupmenu',...
              'String',{'Factory','Custom'},...
              'Tag','dicomDict');
    uicontrol('Parent',hUip(3),...
              'Enable','on',...
              'Position',[10 15 125 20],...
              'Style','Checkbox',...
              'String','Link Image Axes',...
              'Tag','linkAxes',...
              'TooltipString',sprintf('%s\n%s',...
                                      'Links main QUATTRO axes properties',...
                                      'with stand-alone map windows'));

    % Prepare text
    uicontrol('Parent',hUip(1),...
              'Position',[8 23 90 20],...
              'Style','text',...
              'String','# of processors:',...
              'Tag','text_nProcessors',...
              'Visible','off');
    uicontrol('Parent',hUip(2),...
              'Position',[10 126 100 20],...
              'Style','text',...
              'String','Load Directory:',...
              'Tag','text_loadDir');
    uicontrol('Parent',hUip(2),...
              'Position',[10 79 100 20],...
              'Style','text',...
              'String','Save Directory:',...
              'Tag','text_saveDir');
    uicontrol('Parent',hUip(2),...
              'Position',[10 32 100 20],...
              'Style','text',...
              'String','Import Directory:',...
              'Tag','text_importDir');
    uicontrol('Parent',hUip(3),...
              'Position',[10 50 75 20],...
              'Style','text',...
              'String','DICOM Dict.:',...
              'Tag','text_dicomDict');

    % Grab the handles structure for updating the initial GUI values
    hs = guihandles(hFig);

    % Set options and application data
    userOpts = {'parallel',...
                'nProcessors',...
                'loadDir',...
                'saveDir',...
                'importDir',...
                'linkAxes'};
    cellfun(@(x) assign_values(hs.(x),obj.opts.(x)),userOpts);

    % Handle the parallel computation options (since these will be machine
    % dependent).
    if is_par==0
        set(hs.parallel, 'Enable','off', 'Value',false);
        obj.parallel = false;
    elseif is_par>0
        set(hs.parallel, 'Enable','on', 'Value',obj.opts.parallel);
    end
    if get(hs.parallel,'Value')
        set([hs.nProcessors hs.text_nProcessors],'Visible','on');
    end

    % Set the standard application data
    setappdata(hFig,'qtExamObject',obj);
    setappdata(hFig,'qtOptsObject',obj.opts);
    setappdata(hFig,'optionNames',userOpts);

    % Special case for the DICOM dictionary pop-up
    set( findobj(hFig,'Tag','dicomDict'), 'Value', 2-obj.opts.isDfltDict );

    % All tools have been initialized at this point. Update the application data
    set_ui_current_value(hFig);

end %useroptsgui


%-------------------------Callback Functions------------------------------------

function dictionary_Callback(hObj,eventdata)

    % Get the value and ensure it has changed
    val    = get(hObj,'Value');
    curVal = getappdata(hObj,'currentvalue');
    if (curVal==val)
        return
    end

    % Grab the options object
    hFig = guifigure(hObj);
    obj  = getappdata(hFig,'qtOptsObject');

    if (val==1)
        obj.dicomDict = 'factory';
    else %val==2

        % Let the user select the new dictionary
        [fName,pName] = uigetfile('.txt','Select DICOM dict.',which('QUATTRO'));
        if isnumeric(fName) || isnumeric(pName)
            set(hObj,'Value',val);
        else

            % Update the qt_options object
            obj.dicomDict = fullfile(pName,fName);

            % Validate that the dictionary has, in fact, changed
            if ~strcmpi( obj.dicomDict, fullfile(pName,fName) )
                set(hObj,'Value',2-obj.isDfltDict);
            end
            
        end

    end

    % Update the application data
    setappdata( hObj, 'currentvalue', get(hObj,'Value') );

end %dictionary_Callback

function parallel_Callback(hObj,eventdata) %#ok<*INUSD>

    hs = guihandles(hObj);
    if get(hObj,'Value')
        set([hs.nProcessors hs.text_nProcessors],...
            'Visible','on');
    else
        set([hs.nProcessors hs.text_nProcessors],...
            'Visible','off');
    end

end %parallel_Callback